app:
  name: php-app
  replicaCount: 2
  image:
    repository: vikasbandili007/tours
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 8081
    targetPort: 80
    nodePort: 30081
  persistence:
    storageClass: hostpath
    size: 1Gi
    mountPath: /var/www/html/storage

database:
  name: db
  image:
    repository: vikasbandili007/tours
    tag: latest
    pullPolicy: IfNotPresent
  service:
    port: 3306
  persistence:
    storageClass: hostpath
    size: 1Gi

admin:
  name: admin
  replicaCount: 1
  image:
    repository: vikasbandili007/tours
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 8080
    targetPort: 8080
    nodePort: 30080

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
  hosts:
    - host: "localhost"
      paths:
        - path: /
          pathType: Prefix
          serviceName: php-app-service
          servicePort: 8081
        - path: /admin
          pathType: Prefix
          serviceName: admin-service
          servicePort: 8080

configMap:
  name: app-config
  phpVersion: "5.6"
  adminUser: "admin"
  dbName: "tms"

secret:
  dbUser: tmsuser
  dbPassword: tmspassword
  mysqlRootPassword: rootpassword
