apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.admin.name }}-service
spec:
  selector:
    app: {{ .Values.admin.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.admin.service.port }}
      targetPort: {{ .Values.admin.service.targetPort }}
      nodePort: {{ .Values.admin.service.nodePort }}
  type: {{ .Values.admin.service.type }}